clerical_work_reduction/clerical_work_reduction/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('time_management/', include('time_management_app.urls')),
    path('admin/', admin.site.urls),
]

clerical_work_reduction/time_management_app/urls.py
from django.urls import path
from . import views

app_name = 'time_management_app'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('month/', views.MonthView.as_view(), name='month'),
    path('config/', views.ConfigView.as_view(), name='config'),
]

clerical_work_reduction/time_management_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    address = models.CharField(max_length=50, blank=True, verbose_name='住所')

    def __str__(self):
        return self.username


class ContractCompanies(models.Model):
    name = models.CharField(max_length=50, verbose_name='会社名')
    address = models.CharField(max_length=50, blank=True, verbose_name='会社住所')
    zip_code = models.CharField(max_length=8, blank=True, verbose_name='郵便番号')
    president = models.CharField(max_length=20, blank=True, verbose_name='代表名')
    phone_number = models.CharField(
        max_length=12, blank=True, verbose_name='電話番号')
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, verbose_name='ユーザー')

    class Meta:
        verbose_name = "契約会社"
        constraints = [
            models.UniqueConstraint(
                fields=["name", "user"],
                name="company_unique"
            ),
        ]

    def __str__(self):
        return self.name


class SalesPeople(models.Model):
    first_name = models.CharField(max_length=10, verbose_name='名')
    last_name = models.CharField(max_length=10, verbose_name='氏')
    email = models.EmailField(max_length=200, blank=True, verbose_name='Eメール')
    mobile_phone_number = models.CharField(
        max_length=13, blank=True, verbose_name='携帯電話番号')
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, verbose_name='ユーザー')
    company = models.ForeignKey(
        ContractCompanies, on_delete=models.PROTECT, verbose_name='契約会社')

    class Meta:
        verbose_name = "営業"
        constraints = [
            models.UniqueConstraint(
                fields=["first_name", "last_name", "user", "company"],
                name="salespeople_unique"
            ),
        ]

    def __str__(self):
        return self.first_name


class Projects(models.Model):
    project_name = models.CharField(max_length=100, verbose_name='プロジェクト名')
    start_date = models.DateField(max_length=2, verbose_name='契約開始日')
    last_date = models.DateField(max_length=2, verbose_name='契約終了日')
    upper_work_hours = models.IntegerField(verbose_name='稼働上限時間')
    lower_work_hours = models.IntegerField(verbose_name='稼働下限時間')
    assigned_job = models.CharField(
        max_length=50, blank=True, verbose_name='担当業務')
    summary = models.CharField(max_length=100, blank=True, verbose_name='概要')
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, verbose_name='ユーザー')
    company = models.ForeignKey(
        ContractCompanies, on_delete=models.PROTECT, verbose_name='契約会社')

    class Meta:
        verbose_name = "プロジェクト"

    def __str__(self):
        return self.project_name


class WorkPattern(models.Model):
    start_time = models.TimeField(verbose_name='勤務開始時刻')
    close_time = models.TimeField(verbose_name='勤務終了時刻')
    start_break_time = models.TimeField(verbose_name='休憩開始時刻')
    close_break_time = models.TimeField(verbose_name='休憩終了時刻')
    start_overtime_break = models.TimeField(verbose_name='時間外休憩開始時刻')
    close_overtime_break = models.TimeField(verbose_name='時間外休憩終了時刻')
    round_down_unit = models.IntegerField(verbose_name='時間切捨単位')

    class Meta:
        verbose_name = "ワークパターン"

    def __str__(self):
        return str(self.start_time) + "-" + str(self.close_time) + " ("+str(self.round_down_unit)+"単位"+")"


class Attendance(models.Model):
    date = models.DateField(verbose_name='年月日')
    start_time = models.TimeField(verbose_name='勤務開始時刻')
    close_time = models.TimeField(verbose_name='勤務終了時刻')
    today_todo = models.TextField(verbose_name='本日のToDo', blank=True)
    today_issue = models.TextField(verbose_name='進捗と課題', blank=True)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, verbose_name='ユーザー')
    project = models.ForeignKey(
        Projects, on_delete=models.PROTECT, verbose_name='プロジェクト')
    work_pattern = models.ForeignKey(
        WorkPattern, on_delete=models.PROTECT, verbose_name='勤務パターン')

    class Meta:
        verbose_name = "勤怠"
        constraints = [
            models.UniqueConstraint(
                fields=["date", "user", "project"],
                name="attendance_unique"
            ),
        ]

    def __str__(self):
        return self.user.username + " (" + str(self.date) + " " + str(self.start_time) + "~" + str(self.close_time) + ")"

clerical_work_reduction/time_management_app/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


User = get_user_model()


class SignupForm(UserCreationForm):
    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widhet.attrs['placeholder'] = field.label

    class Meta:
        model = User
        fields = ('username',)


class MonthForm(forms.Form):
    start_time = forms.TimeField(label='開始時刻')
    close_time = forms.TimeField(label='終了時刻')
    attend_time = forms.TimeField(label='勤務時間')
    work_time = forms.TimeField(label='稼働時間')
    break_time = forms.TimeField(label='休憩時間')
    overtime_break_time = forms.TimeField(label='時間外休憩時間')
    today_todo = forms.CharField(label='予定')
    today_issue = forms.CharField(label='進捗')

clerical_work_reduction/time_management_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, TemplateView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import LoginForm, SignupForm, MonthForm
from .models import Attendance
from . import mixins
import calendar
import datetime
from collections import defaultdict


class LoginView(LoginView):
    form_class = LoginForm
    template_name = 'time_management_app/login.html'


class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'time_management_app/login.html'


class SignUpView(CreateView):
    form_class = SignupForm
    template_name = 'time_management_app/signup.html'

    def form_valid(self, form):
        user = form.save()
        return redirect('time_management_app:home')


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'time_management_app/home.html'


class MonthView(mixins.MonthCalendarMixin, LoginRequiredMixin, TemplateView):
    form_class = MonthForm
    template_name = 'time_management_app/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_calendar_data()
        context.update(calendar_context)
        return context


class ConfigView(LoginRequiredMixin, TemplateView):
    template_name = 'time_management_app/config.html'

clerical_work_reduction/time_management_app/templates/time_management_app/base.html
{% load static %}
<!doctype html>
<html lang = "ja">
   <head>
       <!-- Required meta tags -->
        <meta charset = "utf-8">
        <meta name = "viewport" content = "width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity = "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin = "anonymous">
        
        <title> {% block title %}{% endblock %} </title>
    </head>

    <body>
       <!-- mt: mergin top 5 -->
        <div class = "container mt-5"></div>

        <!-- body content block -->
        {% block content %}{% endblock %}

        <!-- Optional JavaScript -->
        <!-- Vue first, then Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
        <script src = "{% static 'js/home.js' %}"></script>
        <script src = "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

clerical_work_reduction/time_management_app/templates/time_management_app/config.html
<!-- base.htmlを引き継ぐ -->
{% extends "time_management_app/base.html" %}
<!-- タイトルブロック -->
{% block title %}Login{% endblock %}
<!-- コンテンツブロック -->
{% block content %}
    <a href="{% url 'time_management_app:login' %}"class="btn btn-primary btn-lg btn-block">ログアウト</a>
{% endblock %}

clerical_work_reduction/time_management_app/templates/time_management_app/home.html
<!-- base.htmlを引き継ぐ -->
{% extends "./base.html" %}
<!-- タイトルブロック -->
{% block title %}Login{% endblock %}
<!-- コンテンツブロック -->
{% block content %}
<!-- mt: mergin top  mb: mergin bottom -->
<h1 class = "h1 mt-2 mb-3 font-weight-normal"> home </h1>
<!-- 文字を中央揃えに -->
<div class = "text-center">
    
    <div id = "app">
        <p> [[date]] </p>
        <p> [[time]] </p>
    </div>
    <a href = "{% url 'time_management_app:month' %}"class = "btn btn-primary btn-lg btn-block">退勤</a>
    <a href = "{% url 'time_management_app:month' %}"class = "btn btn-primary btn-lg btn-block">月次表</a>
    <a href = "{% url 'time_management_app:config' %}"class = "btn btn-primary btn-lg btn-block">設定</a>
    <a href = "{% url 'time_management_app:login' %}"class = "btn btn-primary btn-lg btn-block">ログアウト</a>
</div >
{% endblock %}

clerical_work_reduction/time_management_app/templates/time_management_app/login.html
<!-- base.htmlを引き継ぐ -->
{% extends "time_management_app/base.html" %}
<!-- タイトルブロック -->
{% block title %}Login{% endblock %}
<!-- コンテンツブロック -->
{% block content %}

<!-- mt: mergin top  mb: mergin bottom -->
<h1 class="h1 mt-2 mb-3 font-weight-normal">Login</h1>
<!-- 文字を中央揃えに -->
<div class="text-center">
    <form action="" method="POST">
        <!-- card/card-bodyにより外枠が表示される -->
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label }}
                    <br>
                    {{ field }}
                    <br>
                    {{ field.errors }}
                    {{ form.errors }}
                {% endfor %}
                <br>
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        <p>{{ error }}</p>
                    <div>
                {% endfor %}
            <!-- btn-primary:青色ボタン -->
            <button class="btn btn-primary btn-lg btn-block" type="submit">ログイン</button>
            <a href="{% url 'time_management_app:signup' %}"class="btn btn-primary btn-lg btn-block">サインアップ</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

clerical_work_reduction/time_management_app/templates/time_management_app/month.html
<!-- base.htmlを引き継ぐ -->
{% extends "time_management_app/base.html" %}
<!-- タイトルブロック -->
{% block title %}Login{% endblock %}
<!-- コンテンツブロック -->
{% block content %}
    <table class = "table">
        <thead>
           <tr>
                <td> 日(曜日) </td>
                <td> 開始時刻 </td>
                <td> 終了時刻 </td>
                <td> 勤務時間 </td>
                <td> 稼働時間 </td>
                <td> 休憩時間 </td>
                <td> 時間外休憩時間 </td>
                <td> 予定 </td>
                <td> 進捗・課題 </td>
            </tr>
        </thead>
        <tbody>
        {% for key, value in calendar_data.items %}
            <form method = "post">
            <tr>
                <td> {{ key }}日({{ value.weekday }})</td>
                <td> <input type="time" value="{{ value.start_time }}"></td>
                <td> <input type="time" value="{{ value.close_time }}"></td>
                <td> <input type="time" value="{{ value.attend_time }}"></td>
                <td> <input type="time" value="{{ value.work_time }}"></td>
                <td> <input type="time" value="{{ value.break_time }}"></td>
                <td> <input type="time" value="{{ value.overtime_break_time }}"></td>
                <td> <input type="text" value="{{ value.today_todo }}"></td>
                <td> <input type="text" value="{{ value.today_issue }}"></td>
                <td> <button type="submit">送信</button></td>
            </tr >
            </form >
        {% endfor %}
        </tbody>
    </table>
    <a href = "{% url 'time_management_app:login' %}" class="btn btn-primary btn-lg btn-block">ログアウト</a>
{% endblock %}

clerical_work_reduction/time_management_app/templates/time_management_app/signup.html
<!-- base.htmlを引き継ぐ -->
{% extends "time_management_app/base.html" %}
<!-- タイトルブロック -->
{% block title %}Sign up{% endblock %}
<!-- コンテンツブロック -->
{% block content %}

<!-- mt: mergin top  mb: mergin bottom -->
<h1 class="h1 mt-2 mb-3 font-weight-normal">Singn up</h1>
<!-- 文字を中央揃えに -->
<div class="text-center">
    <form action="" method="POST">
        <!-- card/card-bodyにより外枠が表示される -->
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                <label>ユーザーID</label>
                {{ form.username }}
                {{ form.username.errors }}
                <br>
                <label>パスワード</label>
                {{ form.password1 }}
                {{ form.password1.errors }}
                <br>
                <label>パスワード（確認用）</label>
                {{ form.password2 }}
                {{ form.password2.errors }}
                <br>
            <!-- btn-primary:青色ボタン -->
            <button class="btn btn-primary btn-lg btn-block" type="submit">登録</button>
            <a href="{% url 'time_management_app:login' %}"class="btn btn-primary btn-lg btn-block">ログアウト</a>
            </div>
        </div>
    </form>
</div> 
{% endblock %}